export const UNFOLLOWING_USERS_REQUEST = "UNFOLLOWING_USERS_REQUEST";
export const UNFOLLOWING_USERS_SUCCESS = "RUNFOLLOWING_USERS_SUCCESS";
export const UNFOLLOWING_USERS_FAILURE = "UNFOLLOWING_USERS_FAILURE";
