export const CREATE_POST_REQUEST = "CRESTE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
